# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  commands:
    - apt purge pandoc
    - wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
    - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
    - rm pandoc-2.9.2.1-1-amd64.deb

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

python:
  install:
    - requirements: requirements.txt
